spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: com.khs.toy.platform.common.config.CustomPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: none
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    database: mysql
    hibernate.ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/platform
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/platform
      username: khs
      password: qwer1234
